const books = [
    {
        id: "1",
        title: "Colorado's Fourtneers",
        author: "Gerry Roach",
        coverUrl: "",
        spineColor: "#00bbf0",
        status: "Adventure Mode",
        description: "Mountaineering book with maps and route info necessary to climb all 53 of Colorado's 14,000' mountains.",
    },
    {
        id: "2",
        title: "Things Fall Apart",
        author: "Chinua Achebe",
        coverUrl: "",
        spineColor: "#ffc93c",
        status: "Global Voices",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "3",
        title: "The Humans",
        author: "Matt Haig",
        coverUrl: "",
        spineColor: "#d63447",
        status: "Global Voices",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "4",
        title: "Educated",
        author: "Tara Westover",
        coverUrl: "",
        spineColor: "#e8d5b7",
        status: "impactful memoir",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "5",
        title: "Sapiens",
        author: "Yuval Noah Harari",
        coverUrl: "",
        spineColor: "#f6eedf",
        status: "big thinkers",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "6",
        title: "The Glass Castle",
        author: "Jeannette Walls",
        coverUrl: "",
        spineColor: "#ffb6b9",
        status: "impactful memoir",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "7",
        title: "Astrophysics for People in a Hurry",
        author: "Neil deGrasse Tyson",
        coverUrl: "",
        spineColor: "#404b69",
        status: "big thinkers",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
      },
]

export default books