const books = [
    {
        id: "1",
        title: "Colorado's Fourtneers",
        author: "Gerry Roach",
        coverUrl: "/colorado.png",
        spineColor: "#00bbf0",
        status: "Adventure Mode",
        description: "Mountaineering book with maps and route info necessary to climb all 53 of Colorado's 14,000' mountains.",
    },
    {
        id: "2",
        title: "Things Fall Apart",
        author: "Chinua Achebe",
        coverUrl: "/thingsfallapart.png",
        spineColor: "#ffc93c",
        status: "Global Voices",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "3",
        title: "The Humans",
        author: "Matt Haig",
        coverUrl: "",
        spineColor: "#d63447",
        status: "Global Voices",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "4",
        title: "Educated",
        author: "Tara Westover",
        coverUrl: "",
        spineColor: "#e8d5b7",
        status: "impactful memoir",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "5",
        title: "Sapiens",
        author: "Yuval Noah Harari",
        coverUrl: "",
        spineColor: "#f6eedf",
        status: "big thinkers",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "6",
        title: "The Glass Castle",
        author: "Jeannette Walls",
        coverUrl: "",
        spineColor: "#ffb6b9",
        status: "impactful memoir",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "7",
        title: "Astrophysics for People in a Hurry",
        author: "Neil deGrasse Tyson",
        coverUrl: "",
        spineColor: "#404b69",
        status: "big thinkers",
        description: "Things Fall Apart by Chinua Achebe is a novel set in pre-colonial Nigeria that follows the tragic downfall of Okonkwo as British colonization and Christianity begin to disrupt traditional Igbo society in late 19th-century Africa.",
    },
    {
        id: "8",
        title: "Random Title Random Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "9",
        title: "Random",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "10",
        title: "Rand",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "11",
        title: "Random Title Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "12",
        title: "Rando",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "13",
        title: "Random Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "14",
        title: "Random Title",
        author: "Neil deGrasse Tyson",
        coverUrl: "",
        spineColor: "",
        status: " ",
        description: "",
    },
    {
        id: "15",
        title: "Random Title Random Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "16",
        title: "Random",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "17",
        title: "Rand",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "18",
        title: "Random Title Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "19",
        title: "Rando",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "20",
        title: "Random Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "21",
        title: "Rando",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "22",
        title: "Random Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "23",
        title: "Rando",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "24",
        title: "Random Title",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    {
        id: "25",
        title: "Rando",
        author: "Random Author",
        coverUrl: "",
        spineColor: "",
        status: "",
        description: "Testing",
    },
    
]

export default books;
